### ISSUE TITLE
I cann't import your app into Android Studio

### ISSUE THREAD

**Issue by zhaokidd** [Yasic/WifiRecorder#1]
#### I cann't import you app

Everytime i import the app, the ide will show the message

```
plugin with id 'com.android.application' not found.
```

or 

```
plugin with id 'realam android ' not found.
```

I tried every solution i found in stackoverflow or other website,but nether work at all.
Do you have any suggestion?

**Comment by Yasic** [comment]
I used Realm as my database helper in my application and the message shows that it has some error in your project. 
You need to find the solution here I think : https://realm.io/docs/java/latest/#getting-started
